#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED=$'\e[0;31m'
NC=$'\e[0m'

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    exec < /dev/tty && node_modules/.bin/cz --hook || true
fi

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
    echo "${RED}Aborting commit. Your commit message format is not commitizen friendly.${NC}" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "${RED}Aborting commit. Your commit message is too long.${NC}" >&2
    exit 1
fi
